// Generated by https://quicktype.io

export interface StripeSubscription {
  id: string;
  object: string;
  application: null;
  application_fee_percent: null;
  automatic_tax: AutomaticTax;
  billing_cycle_anchor: number;
  billing_cycle_anchor_config: null;
  billing_thresholds: null;
  cancel_at: number;
  cancel_at_period_end: boolean;
  canceled_at: number;
  cancellation_details: CancellationDetails;
  collection_method: string;
  created: number;
  currency: string;
  current_period_end: number;
  current_period_start: number;
  customer: string;
  days_until_due: null;
  default_payment_method: DefaultPaymentMethod;
  default_source: null;
  default_tax_rates: any[];
  description: null;
  discount: null;
  ended_at: number;
  invoice_settings: InvoiceSettings;
  items: Items;
  latest_invoice: string;
  livemode: boolean;
  metadata: Metadata;
  next_pending_invoice_item_invoice: null;
  on_behalf_of: null;
  pause_collection: null;
  payment_settings: PaymentSettings;
  pending_invoice_item_interval: null;
  pending_setup_intent: null;
  pending_update: null;
  plan: Plan;
  quantity: number;
  schedule: null;
  start_date: number;
  status: string;
  test_clock: null;
  transfer_data: null;
  trial_end: null;
  trial_settings: TrialSettings;
  trial_start: null;
}

export interface AutomaticTax {
  enabled: boolean;
  liability: null;
}

export interface CancellationDetails {
  comment: null;
  feedback: null;
  reason: string;
}

export interface DefaultPaymentMethod {
  id: string;
  object: string;
  billing_details: BillingDetails;
  card: Card;
  created: number;
  customer: string;
  livemode: boolean;
  metadata: Metadata;
  type: string;
}

export interface BillingDetails {
  address: Address;
  email: string;
  name: null;
  phone: null;
}

export interface Address {
  city: null;
  country: null;
  line1: null;
  line2: null;
  postal_code: string;
  state: null;
}

export interface Card {
  brand:
    | "amex"
    | "diners"
    | "discover"
    | "eftpos_au"
    | "jcb"
    | "mastercard"
    | "unionpay"
    | "visa"
    | "unknown";
  checks: Checks;
  country: string;
  display_brand: string;
  exp_month: number;
  exp_year: number;
  fingerprint: string;
  funding: string;
  generated_from: null;
  last4: string;
  networks: Networks;
  three_d_secure_usage: ThreeDSecureUsage;
  wallet: null;
}

export interface Checks {
  address_line1_check: null;
  address_postal_code_check: string;
  cvc_check: string;
}

export interface Networks {
  available: string[];
  preferred: null;
}

export interface ThreeDSecureUsage {
  supported: boolean;
}

export interface Metadata {}

export interface InvoiceSettings {
  account_tax_ids: null;
  issuer: Issuer;
}

export interface Issuer {
  type: string;
}

export interface Items {
  object: string;
  data: Datum[];
  has_more: boolean;
  total_count: number;
  url: string;
}

export interface Datum {
  id: string;
  object: string;
  billing_thresholds: null;
  created: number;
  metadata: Metadata;
  plan: Plan;
  price: Price;
  quantity: number;
  subscription: string;
  tax_rates: any[];
}

export interface Plan {
  id: string;
  object: string;
  active: boolean;
  aggregate_usage: null;
  amount: number;
  amount_decimal: string;
  billing_scheme: string;
  created: number;
  currency: string;
  interval: string;
  interval_count: number;
  livemode: boolean;
  metadata: Metadata;
  nickname: null;
  product: string;
  tiers_mode: null;
  transform_usage: null;
  trial_period_days: null;
  usage_type: string;
}

export interface Price {
  id: string;
  object: string;
  active: boolean;
  billing_scheme: string;
  created: number;
  currency: string;
  custom_unit_amount: null;
  livemode: boolean;
  lookup_key: null;
  metadata: Metadata;
  nickname: null;
  product: string;
  recurring: Recurring;
  tax_behavior: string;
  tiers_mode: null;
  transform_quantity: null;
  type: string;
  unit_amount: number;
  unit_amount_decimal: string;
}

export interface Recurring {
  aggregate_usage: null;
  interval: string;
  interval_count: number;
  trial_period_days: null;
  usage_type: string;
}

export interface PaymentSettings {
  payment_method_options: null;
  payment_method_types: null;
  save_default_payment_method: null;
}

export interface TrialSettings {
  end_behavior: EndBehavior;
}

export interface EndBehavior {
  missing_payment_method: string;
}
