import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserNav } from "@/components/UserNav";
import { List, Search } from "react-bootstrap-icons";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const navbarHeight = "64px";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed top-0 z-10 flex flex-col w-full shadow-xl bg-slate-800">
          <div className="border-b">
            <div className="flex items-center px-1 md:px-4 h-14">
              <button className="px-2 py-1 text-sm transition rounded hover:bg-slate-600">
                <List size={30} />
              </button>
              <Link href="/">
                <div className="flex items-center px-2 py-3 cursor-pointer">
                  osu!
                  <span className="font-semibold text-gray-50">Collector</span>
                </div>
              </Link>
              <nav className="items-center hidden mx-6 space-x-4 lg:space-x-6 md:flex">
                <Link
                  href="/all"
                  className="text-sm font-medium transition-colors hover:text-primary"
                >
                  Collections
                </Link>
                <Link
                  href="/tournaments"
                  className="text-sm font-medium transition-colors text-muted-foreground hover:text-primary"
                >
                  Tournaments
                </Link>
                <Link
                  href="client"
                  className="text-sm font-medium transition-colors text-muted-foreground hover:text-primary"
                >
                  App
                </Link>
                <Link
                  href="/users"
                  className="text-sm font-medium transition-colors text-muted-foreground hover:text-primary"
                >
                  Users
                </Link>
              </nav>
              <div className="items-center hidden ml-auto space-x-4 md:flex">
                <div>
                  <div className="relative w-full">
                    <div className="absolute inset-y-0 flex items-center pointer-events-none start-0 ps-3">
                      <Search />
                    </div>
                    <input
                      type="text"
                      className="text-sm rounded-lg block w-full ps-10 p-2.5  bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500"
                      placeholder="Search..."
                      required
                    />
                  </div>
                </div>
                <UserNav />
              </div>
            </div>
          </div>
        </div>
        <div style={{ paddingTop: navbarHeight }}>{children}</div>
      </body>
    </html>
  );
}
